"""Initial CareRouteAI database

Revision ID: f1d882b04650
Revises: 
Create Date: 2026-08-24 21:16:54.242072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d882b04650'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('hospital_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('emergency_available', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_table('rag_documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('specialties',
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('specialty_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('translations',
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('translation_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('doctors',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(length=100), nullable=True),
    sa.Column('consultation_fee', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.specialty_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('hospital_locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('hospital_specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.String(length=50), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.specialty_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_knowledge',
    sa.Column('knowledge_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=150), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('causes', sa.Text(), nullable=True),
    sa.Column('precautions', sa.Text(), nullable=True),
    sa.Column('general_information', sa.Text(), nullable=True),
    sa.Column('emergency_signs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.document_id'], ),
    sa.PrimaryKeyConstraint('knowledge_id')
    )
    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('symptom_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('ai_predictions',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('predicted_condition', sa.String(length=150), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['symptom_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.String(length=50), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('appointment_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['symptom_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('emergency_alerts',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('emergency_type', sa.String(length=100), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('trigger_reason', sa.String(length=200), nullable=True),
    sa.Column('action_taken', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['symptom_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('hospital_recommendations',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.String(length=50), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('specialty_match', sa.Boolean(), nullable=True),
    sa.Column('wait_time', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('recommendation_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['symptom_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['symptom_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('symptom_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('question_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['symptom_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('prediction_scores',
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=150), nullable=True),
    sa.Column('probability_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['ai_predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_table('queue_tokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('token_number', sa.String(length=20), nullable=True),
    sa.Column('queue_status', sa.String(length=20), nullable=True),
    sa.Column('estimated_wait_minutes', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_tokens')
    op.drop_table('prediction_scores')
    op.drop_table('notifications')
    op.drop_table('symptom_answers')
    op.drop_table('reports')
    op.drop_table('hospital_recommendations')
    op.drop_table('emergency_alerts')
    op.drop_table('appointments')
    op.drop_table('ai_predictions')
    op.drop_table('symptom_sessions')
    op.drop_table('patients')
    op.drop_table('medical_knowledge')
    op.drop_table('hospital_specialties')
    op.drop_table('hospital_locations')
    op.drop_table('doctors')
    op.drop_table('users')
    op.drop_table('translations')
    op.drop_table('specialties')
    op.drop_table('rag_documents')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
